google-cred:
  credFilePath: '/keys/client_secret_driveutil.json'
  googleTokensDirPath: 'src/main/resources/google-tokens'
  downloadFolderName: 'Google drive'
yandex-body:
  clientId: '017c21efe04649d5970324b2e3b6bf5f'
  clientSecret: '938214f05945429d95de65db833f21ce'
  tokenUrl: 'https://oauth.yandex.ru/token'
  redirectUri: 'https://oauth.yandex.ru/authorize?response_type=code&client_id=017c21efe04649d5970324b2e3b6bf5f'
  yandexTokensDirPath: 'src/main/resources/yandex-tokens/'